name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Docker login
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Backend Docker build & push
      - name: Build & Push Backend
        uses: docker/build-push-action@v3
        with:
          context: ./app
          push: true
          tags: pratik7491/shivneri-backend:latest

      # Frontend Docker build & push
      - name: Build & Push Frontend
        uses: docker/build-push-action@v3
        with:
          context: ./frontend
          push: true
          tags: pratik7491/shivneri-frontend:latest



  deploy-to-ec2:
    runs-on: ubuntu-latest
    needs: build-and-push-docker
    steps:
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull <dockerhub-username>/shivneri-backend:latest
            docker stop shivneri-backend || true
            docker rm shivneri-backend || true
            docker run -d --name shivneri-backend -p 8080:8080 <dockerhub-username>/shivneri-backend:latest
